name: Build frontend app

on:
  workflow_dispatch:
  push:
    branches:
      - frontend
    paths:
      - '.github/workflows/frontend-ci.yml'
      - 'frontend/**'

env:
  USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
  REGISTRY: ghcr.io
  IMAGE_NAME: bootcamp-frontend
  IMAGE_VERSION: 1.0.0


jobs:
  build_node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Atualizar repositórios do sistema
      run: sudo apt-get update

    - name: Instalar npm
      run: sudo apt-get -y install npm

    - name: Instalar Angular CLI
      run: sudo npm install -g @angular/cli

  #  - name: Executar testes
 #   run: ng test

  docker_build_and_push:
    needs: build_node
    name: Build and deploy Frontend with Docker
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GH_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
