name: Build frontend app

defaults:
  run:
    working-directory: "frontend/app"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend
    paths:
    - '.github/workflows/frontend-ci.yml'
    - 'frontend/**'

env:
  USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
  REGISTRY: ghcr.io
  IMAGE_NAME: bootcamp-frontend
  IMAGE_VERSION: 1.0.0

jobs:
  build_node:
    name: Build Frontend app with npm
    runs-on: ubuntu-latest #self-hosted
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Angular
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    # - name: Run server
    #   run: npm run start --port 9876 &

    # - name: Sleep for 15 seconds
    #   run: sleep 15

    - name: Run tests
      run: npm run test

  docker_build_and_push:
    needs: build_node
    name: Build and deploy Frontend with Docker
    runs-on: self-hosted
    permissions:
      packages: write

    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GH_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
        
        
        
